CREATE DATABASE RH;

USE RH;

CREATE TABLE COLABORADORES(
ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME varchar(100) NOT NULL,
NASCIMENTO date NOT NULL,
CIDADE varchar(20) NOT NULL, 
CARGO varchar(20) NOT NULL,
SALARIO float NOT NULL
); 

SELECT * FROM COLABORADORES;

INSERT INTO COLABORADORES(NOME, NASCIMENTO, CIDADE, CARGO, SALARIO) VALUES("Jorge Aparecido", '2002-04-01', "São Paulo","Analista", 4500.75);
INSERT INTO COLABORADORES(NOME, NASCIMENTO, CIDADE, CARGO, SALARIO) VALUES("Maria Fernanda", '1994-06-22', "Campinas", "Estagiário", 1850.57);
INSERT INTO COLABORADORES(NOME, NASCIMENTO, CIDADE, CARGO, SALARIO) VALUES("Sofia Zayas", '1990-08-07', "São Paulo", "Gerente", 8240.50);
INSERT INTO COLABORADORES(NOME, NASCIMENTO, CIDADE, CARGO, SALARIO) VALUES("Roberto Assis", '2001-09-02', "Ribeirão Preto", "Analista", 4500.75);
INSERT INTO COLABORADORES(NOME, NASCIMENTO, CIDADE, CARGO, SALARIO) VALUES("Rodrigo Faro", '2005-06-23', "São Paulo", "Estagiário", 1850.57);

SELECT * FROM COLABORADORES WHERE SALARIO > 2000.00;
SELECT * FROM COLABORADORES WHERE SALARIO < 2000.00;

UPDATE COLABORADORES SET CIDADE = "Ribeirão Pires" WHERE ID = 4;

