CREATE DATABASE ECOMMERCE;

USE ECOMMERCE;

CREATE TABLE PRODUTOS(
ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME varchar(100) NOT NULL,
CATEGORIA varchar(20) NOT NULL,
LOTE int NOT NULL,
ORIGEM varchar(20) NOT NULL, 
LOJA varchar(50) NOT NULL,
VALOR float NOT NULL
); 

INSERT INTO PRODUTOS(NOME, CATEGORIA, LOTE, ORIGEM, LOJA, VALOR) VALUES("Boneco Max Steel", "Infantil", 1078, "Diadema", "Rua Emiliano Zapata, 235", 130.50);
INSERT INTO PRODUTOS(NOME, CATEGORIA, LOTE, ORIGEM, LOJA, VALOR) VALUES("Beyblade Dragão Celestial", "Infanto-Juvenil", 1050, "Ribeirão Preto", "Rua Jorge da Silva, 179", 50);
INSERT INTO PRODUTOS(NOME, CATEGORIA, LOTE, ORIGEM, LOJA, VALOR) VALUES("Boneca Butterfly", "Infantil", 1090, "Campinas", "Rua das Gracas, 180", 550);
INSERT INTO PRODUTOS(NOME, CATEGORIA, LOTE, ORIGEM, LOJA, VALOR) VALUES("Boneca Barbie", "Infantil", 1056, "Campinas", "Rua das Gracas, 180", 250);
INSERT INTO PRODUTOS(NOME, CATEGORIA, LOTE, ORIGEM, LOJA, VALOR) VALUES("Quebra Cabeça Louve 1000 peças", "Infanto-Juvenil", 1070, "Ribeirão Preto", "Rua Jorge da Silva, 179", 500);

UPDATE PRODUTOS SET VALOR = 530 WHERE ID = 5;

SELECT * FROM PRODUTOS WHERE VALOR > 500.00;
SELECT * FROM PRODUTOS WHERE VALOR < 500.00;